.env.example, app/routes.php, composer.json, composer.lock, phpunit.xml, src/Application/Actions/Action.php, src/Application/Actions/Login.php, src/Application/Auth/Token.php, src/Application/Security/Password.php, src/Domain/Credentials.php, src/Domain/Person.php, src/Repository/PersonRepository.php, tests/Application/Actions/CreatePersonTest.php, tests/Application/Actions/LoginTest.php, tests/Application/Auth/TokenTest.php, tests/Application/Middleware/RecaptchaMiddlewareTest.php, tests/Domain/CredentialsTest.php, tests/TestCase.php, tests/TestPeopleTrait.php
And better cover existing stuff in tests
=> ID-6 – add `/v1/auth` and supporting helpers

src/Domain/Person.php, src/Repository/PersonRepository.php
See e.g. https://testingbot.com/members/tests/1fb72962090c-bb90de54e894-be503e3fb24e-166575679446-06796768
=> ID-29 – fix Doctrine semantical error

.circleci/config.yml, Dockerfile, src/Application/Actions/ActionPayload.php, src/Application/Actions/Status.php, tests/Application/Actions/LoginTest.php, tests/Application/Actions/Person/CreateTest.php, tests/Application/Actions/Person/UpdateTest.php, tests/Application/Actions/StatusTest.php
And
* expand tests
* align response formats with other PHP apps
=> ID-24 – check database and proxies in Status Action

.env.example, README.md, app/settings.php, phpunit.xml, src/Application/Actions/Person/Create.php, src/Application/Middleware/RecaptchaMiddleware.php, src/Domain/Credentials.php, src/Domain/Person.php, tests/Application/Middleware/CredentialsRecaptchaMiddlewareTest.php, tests/Application/Middleware/PersonRecaptchaMiddlewareTest.php
For non-Production environments only, to support load testing.
=> INFRA-73 – provide a captcha bypass option

.circleci/config.yml, app/repositories.php, composer.json, composer.lock, psalm-baseline.xml, psalm.xml, src/Application/Actions/Action.php, src/Application/Actions/ChangePasswordUsingToken.php, src/Application/Actions/CreatePasswordResetToken.php, src/Application/Actions/GetCreditFundingInstructions.php, src/Application/Actions/Login.php, src/Application/Actions/Person/Create.php, src/Application/Actions/Person/Get.php, src/Application/Actions/Person/Update.php, src/Application/Actions/Status.php, src/Application/Security/Password.php, src/Client/Mailer.php, src/Domain/PasswordResetToken.php, src/Repository/PasswordResetTokenRepository.php, src/Repository/PersonRepository.php, tests/Application/Actions/ActionTest.php, tests/Application/Actions/RequestPasswordResetTest.php
Add static analysis with Psalm to the build.
We'll only really feel the impact of this and be able to assess how it helps & hinders us as part of whatever other work we do in this codebase with Psalm in place.
=> Id 31 - static analysis

.circleci/config.yml, .gitignore, composer.json, docs/api-docs.html, docs/swagger-initializer.js, src/Application/Actions/ChangePasswordUsingToken.php, src/Application/Actions/CreatePasswordResetToken.php, src/Application/Actions/GetPasswordResetToken.php, tests/Application/Actions/ChangePasswordWithTokenTest.php
Added open api annotations to the three controllers, and also copied the code from mailer to output a copy of the swagger UI as a CircleCI artifeact so we can view the API docs.
=> Id 37 reset password openapi

.circleci/config.yml, composer.json, integrationTests/IntegrationTest.php, integrationTests/PersonRepositoryTest.php, integrationTests/PingSmokeTest.php, integrationTests/bootstrap.php, phpunit-integration.xml, psalm.xml
This is a fairly direct copy of https://github.com/thebiggive/matchbot/pull/501
=> ID-32: Add integrated tests using MySQL

integrationTests/bootstrap.php
No reason these would ever run anyway unless we make a mistake
=> Block integration tests in prod

psalm-baseline.xml, src/Application/Actions/Person/Update.php, tests/Application/Actions/Person/UpdateTest.php
Indicating when a password was set.
=> MAT-295 – set new Customer Stripe metadata field

composer.lock
Consider merging ~once 1+ regression test runs have passed, and~ at a quiet traffic time.
=> Develop -> main

.circleci/config.yml
Token also added to CI env vars
=> Use latest codecov orb

.circleci/config.yml, app/dependencies.php, docker-compose.yml, psalm-baseline.xml, src/Application/Actions/GetDonationFundsTransferInstructions.php, src/Application/Actions/Person/Create.php, src/Application/Actions/Person/Get.php, src/Client/Stripe.php, src/LoadTestServices/Stripe/StubCustomerService.php, tests/Application/Actions/GetDonationFundsTransferInstructionsTest.php, tests/Application/Actions/Person/CreateTest.php, tests/Application/Actions/Person/GetTest.php, tests/Application/Actions/Person/UpdateTest.php
=> ID-43 – improve & standardise use of stubbable Stripe service

deploy/secrets_entrypoint_tasks.sh
Copied from matchbot and very similar to the existing secrents_entrypoint_web.sh in this repo
=> ID-41: Add tasks entry point script

.circleci/config.yml, .gitignore, app/dependencies.php, psalm-baseline.xml, src/Application/Actions/Person/Update.php, src/Domain/Normalizers/HasPasswordNormalizer.php, src/Domain/PasswordResetToken.php, src/Domain/Person.php, src/Domain/TimestampsTrait.php
Following
https://www.doctrine-project.org/2022/11/04/annotations-to-attributes.html , as done at https://github.com/thebiggive/matchbot/commit/6a7a2b5521a57404d193f327a2b58a1d7943578c
=> BG2-2250: Convert Doctrine Annotations to Attributes

app/settings.php
This isn't fixing a new issue, but one that we noticed while checking work from DON-985.
=> DON-985: Don't display error details in production

app/settings.php
With e.g. header `X-Captcha-Bypass: 1`
=> INFRA-132 – support on-demand captcha bypass

.env.example, app/settings.php, docker-compose.yml, phpunit-integration.xml, phpunit.xml, src/Application/Actions/Person/Create.php, src/Application/Middleware/CorsMiddleware.php, src/Application/Middleware/RecaptchaMiddleware.php
No more app-wide env vars for either testing feature
=> INFRA-132 – stub Stripe and bypass captcha only with HTTP header `X-Is-Load-Test`

src/Application/Middleware/CredentialsRecaptchaMiddleware.php, src/Application/Middleware/PersonRecaptchaMiddleware.php, src/Application/Middleware/PlainRecaptchaMiddleware.php, src/Application/Middleware/RecaptchaMiddleware.php, tests/Application/Actions/LoginTest.php, tests/Application/Actions/Person/CreateTest.php, tests/Application/Middleware/CredentialsRecaptchaMiddlewareTest.php, tests/Application/Middleware/PersonRecaptchaMiddlewareTest.php
Can cleanup code & remove these methods later
=> DON-1072: Fix forgot password currently broken in prod & stag

src/Application/Actions/Person/Get.php
Not quite what I would have expected from https://docs.stripe.com/payments/paymentintents/lifecycle#intent-statuses – but in test mode in practice it seems these can be in either of the new statuses, at least sometimes. And we previously supported `requires_action` which the docs imply we should, so that seems safest to keep checking for as well.
=> DON-1085 – expand which Payment Intent statuses are considered for the pending Donation Funds tip balance

integrationTests/GetPersonTest.php, src/Application/Actions/Action.php, src/Application/Actions/Person/Get.php, src/Domain/Person.php, tests/Application/Actions/Person/GetTest.php, tests/MockStripeResponses/pi_list_one_recently_confirmed_customer_balance_tip.json
Set too when getting pending tips info on Person Get
=> DON-1108 – add Person `recently_confirmed_tips_total` property

app/dependencies.php, app/routes.php, src/Application/Actions/Action.php, src/Application/Actions/ChangePasswordUsingToken.php, src/Application/Actions/CreatePasswordResetToken.php, src/Application/Actions/GetPasswordResetToken.php, src/Application/Actions/Person/Create.php, src/Application/Middleware/CaptchaMiddleware.php, tests/Application/Middleware/CredentialsCaptchaMiddlewareTest.php, tests/Application/Middleware/PersonCaptchaMiddlewareTest.php, tests/TestCase.php
Make `x-captcha-code` in header requirement for reset explicit; name remaining operations
=> Minor API docs tidying

identity, src/Application/Commands/CopyExistingPersonRecordsToMatchbot.php, src/Migrations/Version20250103110506.php, src/Repository/PersonRepository.php
…st one for use with copy to matchbot job
=> ID-48: Send all existing person accounts to matchbot

src/Migrations/Version20250106114223.php
Do not merge until after
https://github.com/thebiggive/matchbot/pull/1155 is deployed to staging
=> ID-48: Restart copy of person data to matchbot to include UUIDs

src/Application/Actions/EmailVerificationToken/Create.php
(If we do send token then the process just fails at the last step when they attempt to set the password)
=> ID-47: Don't send token if donor already has an account with password

app/routes.php, src/Application/Actions/ChangePasswordUsingToken.php, src/Application/Actions/Person/Create.php, src/Application/Actions/Person/SetFirstPassword.php, src/Application/Actions/Person/Update.php, src/Domain/Person.php
FE registration page displays
> Validation error: This value is not valid.
If I try to register with a name with 6 digits in it. It's not copy I'd
write but perhaps not worth taking time to change it unless anyone
complains.
=> Don 1101 name fix

app/dependencies.php, src/Application/Actions/Person/Update.php, src/Monolog/Processor/AwsTraceIdProcessor.php
Should make it simpler to gather more data about existing 500s to decide on the next step
=> ID-50 (sort of) – add Monolog processors

src/Application/Handlers/HttpErrorHandler.php
Which means
* add error logs on any `HttpException`; should mean consistent alarms for 500s
* improve traces & tidy up slightly
Largely a copy/paste from MatchBot, except for removing an `instanceof` that was redundant because we also check `instanceof Throwable`.
=> ID-50 – mostly copy MatchBot's HTTP error handler
